/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Models.VerUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author hol33
 */
public class CrearCuenta extends javax.swing.JFrame {
FormNuevoUsuario fu = new FormNuevoUsuario();
    /**
     * Creates new form CrearCuenta
     */
    public CrearCuenta() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Marcatxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Modelotxt = new javax.swing.JTextField();
        Placatxt = new javax.swing.JTextField();
        Tipotxt = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        añofabri = new javax.swing.JTextField();
        TarifaxDiatxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(192, 130, 97));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Marcatxt.setBackground(new java.awt.Color(226, 199, 153));
        Marcatxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Marcatxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel1.add(Marcatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 280, 60));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setText("Registro de Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 430, 70));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Por favor ingrese la informacion necesaria para el registro del Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 30));

        Modelotxt.setBackground(new java.awt.Color(226, 199, 153));
        Modelotxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Modelotxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direccion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel1.add(Modelotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 280, 60));

        Placatxt.setBackground(new java.awt.Color(226, 199, 153));
        Placatxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Placatxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre Completo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel1.add(Placatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 280, 60));

        Tipotxt.setBackground(new java.awt.Color(226, 199, 153));
        Tipotxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Tipotxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel1.add(Tipotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 280, 60));

        btnIngresar.setBackground(new java.awt.Color(210, 180, 140));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 660, 280, 70));

        btnRegresar.setBackground(new java.awt.Color(210, 180, 140));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 790, 130, 40));

        añofabri.setBackground(new java.awt.Color(226, 199, 153));
        añofabri.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        añofabri.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre de Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel1.add(añofabri, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 280, 60));

        TarifaxDiatxt.setBackground(new java.awt.Color(226, 199, 153));
        TarifaxDiatxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TarifaxDiatxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel1.add(TarifaxDiatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 280, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
    
    String nombre = Placatxt.getText();
    String direccion = Modelotxt.getText();
    String telefono = Marcatxt.getText();
    String email = Tipotxt.getText();
    String username = añofabri.getText();
    String contraseña = TarifaxDiatxt.getText();

    
    VerUsuario nuevoUsuario = new VerUsuario();
    nuevoUsuario.setNombre(nombre);
    nuevoUsuario.setDireccion(direccion);
    nuevoUsuario.setTelefono(telefono);
    nuevoUsuario.setEmail(email);
    nuevoUsuario.setUsername(username);
    nuevoUsuario.setContraseña(contraseña);

   
    boolean insercionExitosa = nuevoUsuario.insertarUsuario(nuevoUsuario);

   
    if (insercionExitosa) {
        
        JOptionPane.showMessageDialog(this, "Usuario creado Exitosamente");
        fu.setVisible(true);
        this.dispose();
    } else {
        
        System.out.println("Error al insertar usuario");
    }
        

        

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        fu.show();
        this.dispose();

    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Marcatxt;
    private javax.swing.JTextField Modelotxt;
    private javax.swing.JTextField Placatxt;
    private javax.swing.JTextField TarifaxDiatxt;
    private javax.swing.JTextField Tipotxt;
    private javax.swing.JTextField añofabri;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
