/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Conexion.Clase_Conexion;
import Diseño.DiseñoTabla;
import Models.Autos;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hol33
 */
public class Form_AgregarAuto extends javax.swing.JFrame {
Principal p = new Principal();
    /**
     * Creates new form Form_AgregarAuto
     */
    public Form_AgregarAuto() {
        initComponents();
        DiseñoTabla();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("Disponible");
        model.addElement("No Disponible");
        dispobilidadxt.setModel(model);
        añofabri.addKeyListener(new KeyAdapter(){
    @Override
    public void keyTyped(KeyEvent e) {
        char c = e.getKeyChar();
        if (!Character.isDigit(c)) {
            e.consume(); // Ignorar la tecla si no es un número
        }
    }
    
});
    TarifaxDiatxt.addKeyListener(new java.awt.event.KeyAdapter() {
    @Override
    public void keyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c) && c != '.' || 
            c == '.' && TarifaxDiatxt.getText().contains(".")) {
            evt.consume(); 
        }
    }
});
        mostrarDatosEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Marcatxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Modelotxt = new javax.swing.JTextField();
        Placatxt = new javax.swing.JTextField();
        Tipotxt = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AutoTable = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        dispobilidadxt = new javax.swing.JComboBox<>();
        añofabri = new javax.swing.JTextField();
        TarifaxDiatxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(192, 130, 97));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Marcatxt.setBackground(new java.awt.Color(226, 199, 153));
        Marcatxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Marcatxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel1.add(Marcatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 280, 60));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setText("Registro de Automoviles");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 430, 70));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Por favor ingrese la informacion necesaria para el registro del Auto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        Modelotxt.setBackground(new java.awt.Color(226, 199, 153));
        Modelotxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Modelotxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel1.add(Modelotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 280, 60));

        Placatxt.setBackground(new java.awt.Color(226, 199, 153));
        Placatxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Placatxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Placa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel1.add(Placatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 280, 60));

        Tipotxt.setBackground(new java.awt.Color(226, 199, 153));
        Tipotxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Tipotxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel1.add(Tipotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 280, 60));

        btnIngresar.setBackground(new java.awt.Color(210, 180, 140));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 130, 40));

        btnEliminar.setBackground(new java.awt.Color(210, 180, 140));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, 140, 40));

        btnModificar.setBackground(new java.awt.Color(210, 180, 140));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 760, 280, 40));

        AutoTable.setBackground(new java.awt.Color(226, 199, 153));
        AutoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Modelo", "Marca", "Tipo", "Año Fabricacion", "Tarifa por Dia", "Disponibilidad"
            }
        ));
        jScrollPane1.setViewportView(AutoTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 770, 660));

        btnRegresar.setBackground(new java.awt.Color(210, 180, 140));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        btnBuscar.setBackground(new java.awt.Color(210, 180, 140));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setText("Buscar Auto");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 150, 40));

        dispobilidadxt.setBackground(new java.awt.Color(226, 199, 153));
        dispobilidadxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dispobilidadxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Disponibilidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel1.add(dispobilidadxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 280, 60));

        añofabri.setBackground(new java.awt.Color(226, 199, 153));
        añofabri.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        añofabri.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Año Fabricacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel1.add(añofabri, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 280, 60));

        TarifaxDiatxt.setBackground(new java.awt.Color(226, 199, 153));
        TarifaxDiatxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TarifaxDiatxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tarifa por dia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel1.add(TarifaxDiatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 280, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void DiseñoTabla(){
        AutoTable.setDefaultRenderer(Object.class, new DiseñoTabla());
        AutoTable.setRowHeight(30);
        AutoTable.setRowMargin(10);
        AutoTable.getTableHeader().setBackground(Color.decode("#9A3B3B"));
        AutoTable.getTableHeader().setForeground(Color.white);
        
        Font fuente = new Font("Roboto",Font.BOLD, 12);
        AutoTable.setFont(fuente);
        AutoTable.getTableHeader().setFont(fuente);
        AutoTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        AutoTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        AutoTable.getColumnModel().getColumn(2).setPreferredWidth(20);
        AutoTable.getColumnModel().getColumn(3).setPreferredWidth(20);
        AutoTable.getColumnModel().getColumn(4).setPreferredWidth(20);
        AutoTable.getColumnModel().getColumn(5).setPreferredWidth(20);
        AutoTable.getColumnModel().getColumn(6).setPreferredWidth(20);

    }
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       
    String placa = Placatxt.getText();
    String modelo = Modelotxt.getText();
    String marca = Marcatxt.getText();
    String tipo = Tipotxt.getText();
    String añoString = añofabri.getText();
    int año = Integer.parseInt(añoString);
    boolean dispon;
    double tarifaDia = Double.parseDouble(TarifaxDiatxt.getText());
        if (dispobilidadxt.equals("Disponible")) {
            dispon = true;
        }else {
            dispon = false;
        }
    
    Autos Ag = new Autos();
    
    boolean exito = Ag.agregarAuto(placa, modelo, marca, tipo, año, tarifaDia, dispon);
    if (exito) {
       
        System.out.println("Datos insertados correctamente.");
        
    } else {
        
        System.out.println("Error al insertar datos.");
    }
    
    mostrarDatosEnTabla();
   
        
    }//GEN-LAST:event_btnIngresarActionPerformed
private void mostrarDatosEnTabla() {
    Autos Ag = new Autos();
    ArrayList<Autos> listaautos = Ag.obtenerAutos();
    DefaultTableModel modelo = (DefaultTableModel) AutoTable.getModel();
    modelo.setRowCount(0);

    for (Autos ag : listaautos) {
        String disponibilidadTexto = ag.getDispon() ? "Disponible" : "No Disponible";
        Object[] fila = {ag.getPlaca(), ag.getModelo(), ag.getMarca(), ag.getTipo(), ag.getAnioFabricacion(), ag.getTarifaDiaria(), disponibilidadTexto};
        modelo.addRow(fila);
    }
}
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       
        String placaEliminar = Placatxt.getText();


Autos ag = new Autos();

// Verificar si alguien ha alquilado el auto
if (ag.autoEstaAlquilado(placaEliminar)) {
    JOptionPane.showMessageDialog(null, "No se puede eliminar el auto. Está actualmente alquilado.", "Error", JOptionPane.ERROR_MESSAGE);
} else {
    
    ag.eliminarRegistrosRelacionados(placaEliminar);

    
    int resultado = ag.eliminarAuto(placaEliminar);

    
    if (resultado > 0) {
        JOptionPane.showMessageDialog(null, "Auto eliminado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, "Error al eliminar el auto.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    
    mostrarDatosEnTabla();
}
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
    String placa = Placatxt.getText();
    String modelo = Modelotxt.getText();
    String marca = Marcatxt.getText();
    String tipo = Tipotxt.getText();
    String añoString = añofabri.getText();
    int año = Integer.parseInt(añoString);
    boolean dispon;
    double tarifaDia = Double.parseDouble(TarifaxDiatxt.getText());
    if (dispobilidadxt.getSelectedItem().equals("Disponible")) {
        dispon = true;
    } else {
        dispon = false;
    }

    
    Autos Ag = new Autos();
    int resultado = Ag.editarAuto(placa, modelo, marca, tipo, año, tarifaDia, dispon);

    if (resultado > 0) {
        
        System.out.println("Datos modificados correctamente.");
    } else {
        
        System.out.println("Error al modificar datos.");
    }

    
    mostrarDatosEnTabla();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        p.show();
        this.dispose();


    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        FrmBuscarAuto ba = new FrmBuscarAuto();
        ba.show();
        this.dispose();
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_AgregarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_AgregarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_AgregarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_AgregarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_AgregarAuto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AutoTable;
    private javax.swing.JTextField Marcatxt;
    private javax.swing.JTextField Modelotxt;
    private javax.swing.JTextField Placatxt;
    private javax.swing.JTextField TarifaxDiatxt;
    private javax.swing.JTextField Tipotxt;
    private javax.swing.JTextField añofabri;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> dispobilidadxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
