/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Diseño.DiseñoTabla;
import Models.Autos;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hol33
 */
public class FrmBuscarAuto extends javax.swing.JFrame {

    /**
     * Creates new form FrmBuscarAuto
     */
    public FrmBuscarAuto() {
        initComponents();
        DiseñoTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Tipotxt = new javax.swing.JTextField();
        Placatxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AutoTable = new javax.swing.JTable();
        rbtPlaca = new javax.swing.JRadioButton();
        rbtTipo = new javax.swing.JRadioButton();
        btnRegresar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(192, 130, 97));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tipotxt.setBackground(new java.awt.Color(226, 199, 153));
        Tipotxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Tipotxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel1.add(Tipotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 280, 60));

        Placatxt.setBackground(new java.awt.Color(226, 199, 153));
        Placatxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Placatxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Placa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        jPanel1.add(Placatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 280, 60));

        AutoTable.setBackground(new java.awt.Color(226, 199, 153));
        AutoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Modelo", "Marca", "Tipo", "Año Fabricacion", "Tarifa por Dia", "Disponibilidad"
            }
        ));
        jScrollPane1.setViewportView(AutoTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 770, 660));

        rbtPlaca.setBackground(new java.awt.Color(192, 130, 97));
        rbtPlaca.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        rbtPlaca.setText("BUSCAR POR PLACA");
        rbtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPlacaActionPerformed(evt);
            }
        });
        jPanel1.add(rbtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        rbtTipo.setBackground(new java.awt.Color(192, 130, 97));
        rbtTipo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        rbtTipo.setText("BUSCAR POR TIPO");
        rbtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTipoActionPerformed(evt);
            }
        });
        jPanel1.add(rbtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(210, 180, 140));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 130, 40));

        btnBuscar.setBackground(new java.awt.Color(210, 180, 140));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setText("BUSCAR AUTOS");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 280, 70));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("Para filtrar por ambos no marque ningun circulo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPlacaActionPerformed
        // TODO add your handling code here:
        if (rbtPlaca.isSelected()) {
        Tipotxt.setEnabled(false);
        rbtTipo.setSelected(false);
        Placatxt.setEnabled(true);
        } else {
        Tipotxt.setEnabled(true);
        }
    }//GEN-LAST:event_rbtPlacaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Principal p = new Principal();
        p.show();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
String placa = Placatxt.getText();
    String tipo = Tipotxt.getText();

    Autos autobuscar = new Autos();
    ArrayList<Autos> autos = autobuscar.buscarAutos(placa, tipo);

  
    DefaultTableModel modelo = (DefaultTableModel) AutoTable.getModel();
    modelo.setRowCount(0);

    
    for (Autos auto : autos) {
        modelo.addRow(new Object[]{
            auto.getPlaca(),
            auto.getModelo(),
            auto.getMarca(),
            auto.getTipo(),
            auto.getAnioFabricacion(),
            auto.getTarifaDiaria(),
            auto.isDispon()
        });
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void rbtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTipoActionPerformed
        if (rbtTipo.isSelected()) {
        Placatxt.setEnabled(false);
        rbtPlaca.setSelected(false);
       Tipotxt.setEnabled(true);
        } else {
        Placatxt.setEnabled(true);
        }
    }//GEN-LAST:event_rbtTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBuscarAuto().setVisible(true);
            }
        });
    }
public void DiseñoTabla(){
        AutoTable.setDefaultRenderer(Object.class, new DiseñoTabla());
        AutoTable.setRowHeight(30);
        AutoTable.setRowMargin(10);
        AutoTable.getTableHeader().setBackground(Color.decode("#9A3B3B"));
        AutoTable.getTableHeader().setForeground(Color.white);
        
        Font fuente = new Font("Roboto",Font.BOLD, 12);
        AutoTable.setFont(fuente);
        AutoTable.getTableHeader().setFont(fuente);
        AutoTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        AutoTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        AutoTable.getColumnModel().getColumn(2).setPreferredWidth(20);
        AutoTable.getColumnModel().getColumn(3).setPreferredWidth(20);
        AutoTable.getColumnModel().getColumn(4).setPreferredWidth(20);
        AutoTable.getColumnModel().getColumn(5).setPreferredWidth(20);
        AutoTable.getColumnModel().getColumn(6).setPreferredWidth(20);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AutoTable;
    private javax.swing.JTextField Placatxt;
    private javax.swing.JTextField Tipotxt;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtPlaca;
    private javax.swing.JRadioButton rbtTipo;
    // End of variables declaration//GEN-END:variables
}
