/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Diseño.DiseñoTabla;
import Models.VerPrestamos;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hol33
 */
public class Prestamos_realizados extends javax.swing.JFrame {
    
FormNuevoUsuario fu = new FormNuevoUsuario();
    /**
     * Creates new form Prestamos_realizados
     */
String userInput;
    public Prestamos_realizados() {
        
        initComponents();
        DiseñoTabla();
        mostrarDatosEnTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnpagar = new javax.swing.JButton();
        Placatxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PrestamoTable = new javax.swing.JTable();
        usertxt = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JButton();
        btnRegresar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(192, 130, 97));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnpagar.setBackground(new java.awt.Color(210, 180, 140));
        btnpagar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnpagar.setText("Pagar");
        btnpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagarActionPerformed(evt);
            }
        });
        jPanel1.add(btnpagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 320, 60));

        Placatxt.setBackground(new java.awt.Color(226, 199, 153));
        Placatxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Placatxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Placa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        Placatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacatxtActionPerformed(evt);
            }
        });
        jPanel1.add(Placatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 320, 60));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Ingrese la placa del auto que pagara");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 320, 70));

        PrestamoTable.setBackground(new java.awt.Color(226, 199, 153));
        PrestamoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Username", "Modelo", "Marca", "Placa", "Fecha de inicio", "Fecha de entrega", "Costo Total"
            }
        ));
        jScrollPane1.setViewportView(PrestamoTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 790, 660));

        usertxt.setBackground(new java.awt.Color(226, 199, 153));
        usertxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        usertxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18))); // NOI18N
        usertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertxtActionPerformed(evt);
            }
        });
        jPanel1.add(usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 320, 60));

        btnVerificar.setBackground(new java.awt.Color(210, 180, 140));
        btnVerificar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 320, 60));

        btnRegresar2.setBackground(new java.awt.Color(210, 180, 140));
        btnRegresar2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar2.setText("Regresar");
        btnRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1175, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagarActionPerformed
        
        VerPrestamos ver = new VerPrestamos();
        String placa = Placatxt.getText();
        ver.eliminarDatosPorPlaca(placa);
   
    mostrarDatosEnTabla();
    JOptionPane.showMessageDialog(rootPane, "SE HA REALIZADO EL PAGO GRACIAS POR CONFIAR EN NOSOTROS", "PAGO CONCRETADO", HEIGHT);

    }//GEN-LAST:event_btnpagarActionPerformed

    private void PlacatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlacatxtActionPerformed

    private void usertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertxtActionPerformed
       
    }//GEN-LAST:event_usertxtActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
         userInput = usertxt.getText();
        mostrarDatosEnTabla();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar2ActionPerformed
        FormElegir pa = new FormElegir();
        pa.show();
        this.dispose();
    }//GEN-LAST:event_btnRegresar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamos_realizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamos_realizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamos_realizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamos_realizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamos_realizados().setVisible(true);
            }
        });
    }
public void DiseñoTabla(){
        PrestamoTable.setDefaultRenderer(Object.class, new DiseñoTabla());
        PrestamoTable.setRowHeight(30);
        PrestamoTable.setRowMargin(10);
        PrestamoTable.getTableHeader().setBackground(Color.decode("#9A3B3B"));
        PrestamoTable.getTableHeader().setForeground(Color.white);
        
        Font fuente = new Font("Roboto",Font.BOLD, 12);
        PrestamoTable.setFont(fuente);
        PrestamoTable.getTableHeader().setFont(fuente);
        PrestamoTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        PrestamoTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        PrestamoTable.getColumnModel().getColumn(2).setPreferredWidth(75);
        PrestamoTable.getColumnModel().getColumn(3).setPreferredWidth(75);
        PrestamoTable.getColumnModel().getColumn(4).setPreferredWidth(50);
        PrestamoTable.getColumnModel().getColumn(5).setPreferredWidth(50);
        PrestamoTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        PrestamoTable.getColumnModel().getColumn(6).setPreferredWidth(100);
        PrestamoTable.getColumnModel().getColumn(7).setPreferredWidth(75);
        

    }

private void mostrarDatosEnTabla() {
    VerPrestamos verPrestamos = new VerPrestamos();

    ArrayList<VerPrestamos> listaPrestamos = verPrestamos.obtenerPrestamosPorUsername(userInput);
    DefaultTableModel modelo = (DefaultTableModel) PrestamoTable.getModel();

    modelo.setRowCount(0);

    for (VerPrestamos prestamo : listaPrestamos) {
        Object[] fila = {
            prestamo.getNombrecliente(),
            prestamo.getUsername(),
            prestamo.getModelo(),
            prestamo.getMarca(),
            prestamo.getPlaca(),
            prestamo.getFechainicio(),
            prestamo.getFechaentrega(),
            prestamo.getCostoTotal()
        };
        modelo.addRow(fila);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Placatxt;
    private javax.swing.JTable PrestamoTable;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JButton btnRegresar2;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JButton btnpagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField usertxt;
    // End of variables declaration//GEN-END:variables
}
