/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Diseño.DiseñoTabla;
import Models.VerPrestamos;
import Models.VerUsuario;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hol33
 */
public class VerAutos extends javax.swing.JFrame {

    /**
     * Creates new form VerAutos
     */
    public VerAutos() {
        initComponents();
        DiseñoTabla();
        mostrarDatosEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PrestamoTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(192, 130, 97));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setText("LISTADO DE PRESTAMOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 470, 70));

        btnRegresar.setBackground(new java.awt.Color(210, 180, 140));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 40));

        PrestamoTable.setBackground(new java.awt.Color(226, 199, 153));
        PrestamoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Cliente", "Modelo", "Marca", "Placa", "Fecha de inicio", "Fecha de entrega", "Costo Total"
            }
        ));
        jScrollPane1.setViewportView(PrestamoTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 770, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Principal p = new Principal();
        p.show();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerAutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerAutos().setVisible(true);
            }
        });
    }
public void DiseñoTabla(){
        PrestamoTable.setDefaultRenderer(Object.class, new DiseñoTabla());
        PrestamoTable.setRowHeight(30);
        PrestamoTable.setRowMargin(10);
        PrestamoTable.getTableHeader().setBackground(Color.decode("#9A3B3B"));
        PrestamoTable.getTableHeader().setForeground(Color.white);
        
        Font fuente = new Font("Roboto",Font.BOLD, 12);
        PrestamoTable.setFont(fuente);
        PrestamoTable.getTableHeader().setFont(fuente);
        PrestamoTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        PrestamoTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        PrestamoTable.getColumnModel().getColumn(2).setPreferredWidth(75);
        PrestamoTable.getColumnModel().getColumn(3).setPreferredWidth(75);
        PrestamoTable.getColumnModel().getColumn(4).setPreferredWidth(50);
        PrestamoTable.getColumnModel().getColumn(5).setPreferredWidth(50);
        PrestamoTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        PrestamoTable.getColumnModel().getColumn(6).setPreferredWidth(100);
        PrestamoTable.getColumnModel().getColumn(7).setPreferredWidth(75);
        

    }

public
         void mostrarDatosEnTabla() {
    VerPrestamos verpre = new VerPrestamos();

    
   ArrayList<VerPrestamos> listaPrestamos =  verpre.obtenerAlquiler();
   DefaultTableModel modelo = (DefaultTableModel) PrestamoTable.getModel();
   
   modelo.setRowCount(0);

    
    for (VerPrestamos ver : listaPrestamos) {
        Object[] fila = {ver.getUsername(),ver.getNombrecliente(),ver.getModelo(),ver.getMarca(),ver.getPlaca(),ver.getFechainicio(),ver.getFechaentrega(),ver.getCostoTotal()};
        modelo.addRow(fila);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PrestamoTable;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
